# Site Settings
title: Anudeep Samaiya
email: ""
description: >- # This helps Google understand your page content
  Staff Software Engineer specializing in backend infrastructure, distributed systems, and scalable data platforms.
  Building in Python, Go, Kubernetes, Kafka. Passionate about solving 
  problems and open-source collaboration.
baseurl: "/anudeepsamaiya"
url: "https://anudeepsamaiya.github.io" # the base hostname & protocol for your site

# Social Links
twitter_username: anudeepsamaiya
github_username:  anudeepsamaiya
linkedin_username: anudeepsamaiya

# Search Engine Verification
# Replace 'YOUR_CODE_HERE' with the code from Google Search Console
google_site_verification: "twVFs_dUxCyldlt-Sif72GezMsXbI0wKJEVTBJ1A22g"

# Build Settings
theme: minima
header_pages: [] # Exclude all pages from the header to remove the redundant "About Me" link
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO Plugin Configuration
twitter:
  username: anudeepsamaiya
  card: summary

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
